services:
  apache:
    container_name: hurk.dev-apache-container
    image: httpd:alpine
    restart: always
    networks:
      - 'proxymesh'
      - 'default'
    volumes:
      - "${PWD}/html/:/usr/local/apache2/htdocs/"
      - "${PWD}/config/httpd.conf:/usr/local/apache2/conf/httpd.conf"
networks:
  proxymesh:
    external: true
